name: paperflix_rg
description: From Ayotrust to Everyone.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+6
  firebase_storage: ^3.0.6
  flutter_bcrypt: ^1.0.5
  flutter_typeahead: ^1.7.0

  # redux: ^3.0.0
  # redux_logging: ^0.3.0
  # flutter_redux: ^0.5.3
  # redux_thunk: ^0.2.1
  shared_preferences: ^0.5.4+3
  localstorage: ^3.0.0+3
  dio: ^3.0.4

  i18n: ^0.9.4
  intl: ^0.15.8
  device_info: ^0.4.1+1

  cached_network_image: ^1.1.1
  image_cropper: ^1.1.0
  image_picker: ^0.6.1+10
  cupertino_icons: ^0.1.2
  toast: ^0.1.5
  loading: ^1.0.1
  month_picker_dialog: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/locale/localization_en.json
    - assets/locale/localization_id.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFP_Text
      fonts:
        - asset: fonts/SF_Compact/SF-Compact-Text-Light.otf
          weight: 300
        - asset: fonts/SF_Compact/SF-Compact-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/SF_Compact/SF-Compact-Text-Regular.otf
          weight: 400
        - asset: fonts/SF_Compact/SF-Compact-Text-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/SF_Compact/SF-Compact-Text-Medium.otf
          weight: 500
        - asset: fonts/SF_Compact/SF-Compact-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/SF_Compact/SF-Compact-Text-Bold.otf
          weight: 700
        - asset: fonts/SF_Compact/SF-Compact-Text-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/SF_Compact/SF-Compact-Text-Heavy.otf
          weight: 800
        - asset: fonts/SF_Compact/SF-Compact-Text-HeavyItalic.otf
          weight: 800
          style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
